name: CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --watchAll=false

    - name: Build Docker image
      run: docker build -t zeua/reactprod .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u zeua --password-stdin

    - name: Push Docker image
      run: docker push zeua/reactprod

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}   # tu DNS público de EC2
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }} # tu clave privada (.pem)
        script: |
          # Detener y eliminar contenedor reactprod si existe
          docker stop reactprod || true
          docker rm reactprod || true

          # Detener y eliminar cualquier contenedor que esté usando el puerto 80
          docker ps -q --filter "publish=80" | xargs -r docker stop
          docker ps -q --filter "publish=80" | xargs -r docker rm

          # Descargar la última imagen
          docker pull zeua/reactprod

          # Levantar el nuevo contenedor en el puerto 80
          docker run -d --name reactprod -p 80:3000 zeua/reactprod
